#!/usr/bin/ruby
require 'fileutils'
begin
  require 'rubygems'
rescue LoadError => e
  $stderr.puts "Could not load rubygems. Assuming you know what you are doing..."
end
begin
  require 'daemons'
rescue LoadError => e
  $stderr.puts "Could not load daemons gem. Please install it."
  exit 1
end

path = File.expand_path(File.join(File.dirname(__FILE__)))
FileUtils.mkdir_p File.join(path,"log")

script = File.join(path, "irc.rb")
Daemons.run(script, :log_output=>true, :dir=>File.join(path, "log"), :app_name=>"rirc_bot", :dir_mode=>:normal)
